apiVersion: v1
kind: Namespace
metadata:
  name: evohome-bigquery-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evohome-hgi80-listener
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-hgi80-listener
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evohome-hgi80-listener
  namespace: evohome-bigquery-exporter
  labels:
    app: evohome-hgi80-listener
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: evohome-hgi80-listener
  template:
    metadata:
      labels:
        app: evohome-hgi80-listener
    spec:
      restartPolicy: Always
      serviceAccount: evohome-hgi80-listener
      containers:
      - name: evohome-hgi80-listener
        image: jsalverda/evohome-hgi80-listener:${CONTAINER_TAG}
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "EVOHOME_ID"
          valueFrom:
            configMapKeyRef:
              name: evohome-hgi80-listener-configs
              key: evohome-id
        - name: BQ_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: bq-project-id
              name: evohome-hgi80-listener-configs
        - name: BQ_DATASET
          valueFrom:
            configMapKeyRef:
              key: bq-dataset
              name: evohome-hgi80-listener-configs
        - name: BQ_TABLE
          valueFrom:
            configMapKeyRef:
              key: bq-table
              name: evohome-hgi80-listener-configs
        - name: BQ_ENABLE
          valueFrom:
            configMapKeyRef:
              key: bq-enable
              name: evohome-hgi80-listener-configs
      - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/keyfile.json
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: configs
          mountPath: /configs
        - name: state
          mountPath: /state
        - name: secrets
          mountPath: /secrets
        - name: hgi
          mountPath: /dev/ttyUSB0
      terminationGracePeriodSeconds: 300
      volumes:
      - name: configs
        configMap:
          name: evohome-hgi80-listener-configs
      - name: state
        configMap:
          name: evohome-hgi80-listener-state
      - name: secrets
        secret:
          defaultMode: 420
          secretName: evohome-hgi80-listener-credentials
      - name: hgi
        hostPath:
          path: ${HGI_USB_PATH}