apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evohome-hgi80-listener.fullname" . }}
  labels:
    {{- include "evohome-hgi80-listener.labels" . | nindent 4 }}
data:
  evohome-id: {{ .Values.config.evohomeId | toString }}
  bq-enable: {{ .Values.config.bqEnable | toString }}
  bq-project-id: {{ .Values.config.bqProjectID | toString }}
  bq-dataset: {{ .Values.config.bqDataset | toString }}
  bq-table: {{ .Values.config.bqTable | toString }}