apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evohome-hgi80-listener.fullname" . }}
  labels:
    {{- include "evohome-hgi80-listener.labels" . | nindent 4 }}
data:
  evohome-id: {{ .Values.config.evohomeId | quote }}
  bq-enable: {{ .Values.config.bqEnable | quote }}
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}