apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evohome-hgi80-listener.fullname" . }}
  labels:
    {{- include "evohome-hgi80-listener.labels" . | nindent 4 }}
type: Opaque
data:
  keyfile.json: {{ .Values.secret.gcpServiceAccountKeyfile | toString | b64enc }}